### ISSUE TITLE
打算加点我校研究生课程，有什么建议吗？

### ISSUE THREAD

**Issue by jacklanda** [dashjay/comment-for-USTB-course#2]
在读USTB研一，本学期选了一堆(水)课 x)

- 为了便于区分本科/研究生课程，我需要在首页README的课程名格式上给出标注吗 (e.g. 高等计算机体系结构(研), 计算机网络(本)

**Comment by dashjay** [comment]
感觉可以自由发挥呀，帮我update一下本科标注即可~

**Comment by jacklanda** [comment]
> 感觉可以自由发挥呀，帮我update一下本科标注即可~

 好嘞
